swagger: "2.0"
info:
  description: "API para gerenciar usuários e tarefas"
  version: "1.0.0"
  title: "Task API"
host: "localhost:3000"
basePath: "/"
tags:
  - name: "Users"
    description: "Operações relacionadas a usuários"
  - name: "Auth"
    description: "Autenticação"
  - name: "Tasks"
    description: "Operações relacionadas a tarefas"
paths:
  /users/register:
    post:
      tags:
        - "Users"
      summary: "Registrar um novo usuário"
      description: "Cria um novo usuário"
      operationId: "registerUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Dados do usuário para registro"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        201:
          description: "Usuário criado com sucesso"
        400:
          description: "Requisição inválida"
        409:
          description: "Usuário já existente"

  /auth/login:
    post:
      tags:
        - "Auth"
      summary: "Login de usuário"
      description: "Autentica um usuário e retorna um token JWT"
      operationId: "loginUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Credenciais do usuário"
          required: true
          schema:
            type: "object"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Login bem-sucedido"
        401:
          description: "Credenciais inválidas"

  /tasks:
    get:
      tags:
        - "Tasks"
      summary: "Listar todas as tarefas"
      description: "Retorna todas as tarefas do usuário autenticado"
      operationId: "getTasks"
      produces:
        - "application/json"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Token JWT no formato 'Bearer {token}'"
      responses:
        200:
          description: "Lista de tarefas"
        401:
          description: "Token JWT inválido ou ausente"
    post:
      tags:
        - "Tasks"
      summary: "Criar uma nova tarefa"
      description: "Cria uma nova tarefa para o usuário autenticado"
      operationId: "createTask"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Token JWT no formato 'Bearer {token}'"
        - in: "body"
          name: "body"
          description: "Dados da tarefa para criar"
          required: true
          schema:
            type: "object"
            properties:
              title:
                type: "string"
              description:
                type: "string"
              completed:
                type: "boolean"
                default: false
      responses:
        201:
          description: "Tarefa criada com sucesso"
        401:
          description: "Token JWT inválido ou ausente"

  /tasks/{id}:
    put:
      tags:
        - "Tasks"
      summary: "Atualizar uma tarefa"
      description: "Atualiza uma tarefa existente do usuário autenticado"
      operationId: "updateTask"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da tarefa"
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Token JWT no formato 'Bearer {token}'"
        - in: "body"
          name: "body"
          description: "Dados da tarefa para atualizar"
          required: true
          schema:
            type: "object"
            properties:
              title:
                type: "string"
              description:
                type: "string"
              completed:
                type: "boolean"
      responses:
        200:
          description: "Tarefa atualizada com sucesso"
        401:
          description: "Token JWT inválido ou ausente"
        404:
          description: "Tarefa não encontrada"

    delete:
      tags:
        - "Tasks"
      summary: "Excluir uma tarefa"
      description: "Exclui uma tarefa existente do usuário autenticado"
      operationId: "deleteTask"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          description: "ID da tarefa"
        - name: "Authorization"
          in: "header"
          required: true
          type: "string"
          description: "Token JWT no formato 'Bearer {token}'"
      responses:
        200:
          description: "Tarefa excluída com sucesso"
        401:
          description: "Token JWT inválido ou ausente"
        404:
          description: "Tarefa não encontrada"
